config/routes.rb
Rails.application.routes.draw do
  resources :properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :stations, dependent: :destroy
  accepts_nested_attributes_for :stations
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :property, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
    2.times { @property.stations.build }
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:property_name, :rent, :address, :property_age, :remarks, stations_attributes: [:id, :route_name, :station_name, :walk_fraction])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def set_minute(minute)
    return minute unless minute.present?
	minute.to_s + "分"
  end

  def set_year(year)
	return year unless year.present?
	year.to_s + "年"
  end

  def set_yen(yen)
	return yen unless yen.present?
	yen.to_s(:delimited) + "円"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_for(property) do |f| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property_name %>
    <%= f.text_field :property_name %>
  </div>

  <div class="field">
    <%= f.label :rent %>
    <%= f.number_field :rent, :min => 0  %>円
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :property_age %>
    <%= f.number_field :property_age, :min => 0  %>年
  </div>

  <div class="field">
    <%= f.label :remarks %>
    <%= f.text_area :remarks %>
  </div>

  <hr />
  
  <%= f.fields_for :stations do |stations_form| %>
    <h2>最寄り駅<%= stations_form.index + 1 %></h2>

    <div class="field">
      <%= stations_form.label :route_name %>
      <%= stations_form.text_field :route_name %>
    </div>

    <div class="field">
      <%= stations_form.label :station_name %>
      <%= stations_form.text_field :station_name %>
    </div>

    <div class="field">
      <%= stations_form.label :walk_fraction %>
      <%= stations_form.number_field :walk_fraction, :min => 0 %>分
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>物件編集</h1>

<%= render 'form', property: @property %>

<%= link_to '詳細', @property %> |
<%= link_to '戻る', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>物件一覧</h1>

<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property_name %></td>
        <td><%= set_yen(property.rent) %></td>
        <td><%= property.address %></td>
        <td><%= set_year(property.property_age) %></td>
        <td><%= property.remarks %></td>
        <td><%= link_to '詳細', property %></td>
        <td><%= link_to '編集', edit_property_path(property) %></td>
        <td><%= link_to '削除', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '物件を登録する', new_property_path %>

app/views/properties/new.html.erb
<h1>物件登録</h1>

<%= render 'form', property: @property %>

<%= link_to '戻る', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>物件名:</strong>
  <%= @property.property_name %>
</p>

<p>
  <strong>賃料:</strong>
  <%= set_yen(@property.rent) %>
</p>

<p>
  <strong>住所:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>築年数</strong>
  <%= set_year(@property.property_age) %>
</p>

<p>
  <strong>備考</strong>
  <%= @property.remarks %>
</p>

<hr />

<% @property.stations.each_with_index do |station, i| %>
  <h3>最寄り駅<%= i + 1 %></h3>

  <p>
    <strong>路線名</strong>
    <%= station.route_name %>
  </p>

  <p>
    <strong>駅名</strong>
    <%= station.station_name %>
  </p>

  <p>
    <strong>徒歩分数</strong>
    <%= set_minute(station.walk_fraction) %>
  </p>
<% end %>

<%= link_to '編集', edit_property_path(@property) %> |
<%= link_to '戻る', properties_path %>